#################
#Settings Config#
#################

#DO NOT CHANGE THIS LINE! YOUR CONFIG WILL BE RESET UPON LOADING IF THIS LINE IS EDITED!
Version: 3

#Latest Server News
News: "&bPlease Configure This Plugin!"

#Scoreboard Name
Scoreboard: "&c&lServer Status"

#Server Name
ServerName: "&c&lServer"

#Nexus Location
NexusX: 0
NexusY: 60
NexusZ: 0
NexusWorld: "world"
NexusYaw: 0
NexusPitch: 0