name: Settings
author: WolfLeader116
main: io.github.WolfLeader116.Settings.Settings
version: 1.1.6
description: Settings plugin.
commands:
  Settings:
    description: Settings help command.
  Gamemode:
    description: Gamemode command.
    aliases: [gm,creative,survival,adventure,spectator]
permissions:
  settings.set:
    description: Lets the player set their settings.
  settings.set.other:
    description: Lets the player set other players settings.
  settings.*:
    description: Gives the player all settings permissions.
    children:
      settings.set: true
      settings.set.other: true
      settings.gamemode: true
      settings.gamemode.other: true
  settings.gamemode:
    description: Lets the player set their gamemode.
  settings.gamemode.other:
    description: Lets the player set another player's gamemode.